project:
  type: website
  output-dir: public

website:
  title: "Data 92-13"
  navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
      right:
      - icon: github
        href: https://github.com/CedricMidoux/voteR


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

freeze: true
